<?php

if (!function_exists('allMakes')) {
    function allMakes()
    {
        return [
            'Abarth' => 'Abarth',
            'Acura' => 'Acura',
            'Alfa Romeo' => 'Alfa Romeo',
            'Aston Martin' => 'Aston Martin',
            'Audi' => 'Audi',
            'Bentley' => 'Bentley',
            'BMW' => 'BMW',
            'Bugatti' => 'Bugatti',
            'Buick' => 'Buick',
            'Cadillac' => 'Cadillac',
            'Chevrolet' => 'Chevrolet',
            'Chrysler' => 'Chrysler',
            'Citroen' => 'Citroen',
            'Dacia' => 'Dacia',
            'Daewoo' => 'Daewoo',
            'Daihatsu' => 'Daihatsu',
            'Dodge' => 'Dodge',
            'Ferrari' => 'Ferrari',
            'Fiat' => 'Fiat',
            'Ford' => 'Ford',
            'Genesis' => 'Genesis',
            'GMC' => 'GMC',
            'Honda' => 'Honda',
            'Hummer' => 'Hummer',
            'Hyundai' => 'Hyundai',
            'Infiniti' => 'Infiniti',
            'Isuzu' => 'Isuzu',
            'Jaguar' => 'Jaguar',
            'Jeep' => 'Jeep',
            'Kia' => 'Kia',
            'Koenigsegg' => 'Koenigsegg',
            'Lamborghini' => 'Lamborghini',
            'Land Rover' => 'Land Rover',
            'Lexus' => 'Lexus',
            'Lincoln' => 'Lincoln',
            'Lotus' => 'Lotus',
            'Maserati' => 'Maserati',
            'Mazda' => 'Mazda',
            'McLaren' => 'McLaren',
            'Mercedes-Benz' => 'Mercedes-Benz',
            'Mini' => 'Mini',
            'Mitsubishi' => 'Mitsubishi',
            'Nissan' => 'Nissan',
            'Opel' => 'Opel',
            'Pagani' => 'Pagani',
            'Peugeot' => 'Peugeot',
            'Porsche' => 'Porsche',
            'Ram' => 'Ram',
            'Renault' => 'Renault',
            'Rolls-Royce' => 'Rolls-Royce',
            'Saab' => 'Saab',
            'Seat' => 'Seat',
            'Skoda' => 'Skoda',
            'Smart' => 'Smart',
            'Subaru' => 'Subaru',
            'Suzuki' => 'Suzuki',
            'Tesla' => 'Tesla',
            'Toyota' => 'Toyota',
            'Volkswagen' => 'Volkswagen',
            'Volvo' => 'Volvo',

        ];
    }
}
?>
